#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push caryyu/douban-openapi-server:${TRAVIS_COMMIT:0:7}
docker push caryyu/douban-openapi-server:latest

